version: '3'

services:
    postgres:
        image: postgres:9.6
        container_name: {{cookiecutter.project_slug}}_postgres
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-airflow}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change_me}
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata # persist data on the local filesystem.
        volumes:
            - /var/lib/postgresql/data/pgdata

    webserver:
        image: {{cookiecutter.docker_registry}}/{{cookiecutter.project_slug}}_app:${APP_VERSION}
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=change_me
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
